name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php-version: ['7.4', '8.1', '8.2']
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          node-version: ${{ matrix.php-version }}
          extensions: none, mb_string
      - run: composer install
      - run: composer test
